/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventarioventas.Vista;

import inventarioventas.controlador.ConexionBD;
import inventarioventas.Modelo.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JuanCaCha
 */
public class VistaInventario extends javax.swing.JFrame {

    /**
     * Creates new form VistaInventario
     */
    int id_producto, stock;
    String nombreproducto;
    Cliente cliente = new Cliente();
    ConexionBD conexion = new ConexionBD();
    DefaultTableModel modeloProductos;
    DefaultTableModel modeloClientes;
    DefaultTableModel modeloCaja;
    DefaultTableModel modeloPrestar;
    public VistaInventario() {
        
        initComponents();
        setBounds(0, 0, 570, 560);
        setLocationRelativeTo(null);
        modeloProductos = (DefaultTableModel)Tablaproductos.getModel();
        modeloClientes = (DefaultTableModel)Tablaclientes.getModel();
        modeloCaja = (DefaultTableModel)Tablacaja.getModel();
        modeloPrestar = (DefaultTableModel)Tablaprestar.getModel();
        conexion.obtenerTablacliente(modeloClientes);
        conexion.obtenerTablaproducto(modeloProductos);
        conexion.obtenerTablacaja(modeloCaja);
        conexion.obtenerTablaprestar(modeloPrestar);
        btnCambiarstock.setVisible(false);
        labelstock.setVisible(false);
        stockspin.setVisible(false);
        btnvender.setVisible(false);
        
        Tablaproductos.addMouseListener(new MouseAdapter(){
            DefaultTableModel model = new DefaultTableModel();
            @Override
            public void mouseClicked (MouseEvent e)
                {
                    
                    int i = Tablaproductos.getSelectedRow();
                    id_producto=Integer.parseInt(Tablaproductos.getValueAt(i, 0).toString());
                    stock =Integer.parseInt(Tablaproductos.getValueAt(i, 3).toString());
                    nombreproducto = Tablaproductos.getValueAt(i, 1).toString();
                    
                    btnCambiarstock.setVisible(true);
                    labelstock.setVisible(true);
                    stockspin.setVisible(true);
                    btnvender.setVisible(true);
                    stockspin.setValue(stock);
                    System.out.println(id_producto + "\n" + stock);
                }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pags = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablaproductos = new javax.swing.JTable();
        btnvender = new javax.swing.JButton();
        stockspin = new javax.swing.JSpinner();
        labelstock = new javax.swing.JLabel();
        btnCambiarstock = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tablaclientes = new javax.swing.JTable();
        btagregarcliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfnombrecliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tftelefonocliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfemailcliente = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tablacaja = new javax.swing.JTable();
        btnreportes = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tablaprestar = new javax.swing.JTable();
        btnprestar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfechaprestar = new com.toedter.calendar.JDateChooser();
        nombreprestar = new javax.swing.JTextField();
        suproducto = new javax.swing.JTextField();
        miproducto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Tnombrecliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tnombreproducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfecha = new com.toedter.calendar.JDateChooser();
        btnvenderfinal = new javax.swing.JButton();
        spinerventa = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tablaproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tablaproductos);

        btnvender.setText("Vender");
        btnvender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvenderActionPerformed(evt);
            }
        });

        labelstock.setText("Cambiar Stock");

        btnCambiarstock.setText("Cambiar");
        btnCambiarstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarstockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnCambiarstock)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelstock)
                                .addGap(3, 3, 3)
                                .addComponent(stockspin, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnvender)
                        .addGap(8, 8, 8)))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stockspin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelstock))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCambiarstock))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnvender)
                .addContainerGap())
        );

        pags.addTab("Pruductos", jPanel1);

        Tablaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Telefono", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tablaclientes);

        btagregarcliente.setText("Agregar");
        btagregarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btagregarclienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre:");

        tfnombrecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnombreclienteActionPerformed(evt);
            }
        });

        jLabel6.setText("Telefono:");

        tftelefonocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftelefonoclienteActionPerformed(evt);
            }
        });

        jLabel7.setText("Email:");

        tfemailcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfemailclienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfnombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftelefonocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfemailcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btagregarcliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfnombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftelefonocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfemailcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btagregarcliente)
                .addGap(38, 38, 38))
        );

        pags.addTab("Clientes", jPanel2);

        Tablacaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero Venta", "Productos", "Cantidad productos", "Cliente", "Fecha", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Tablacaja);

        btnreportes.setText("Reportes");
        btnreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnreportes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnreportes)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pags.addTab("Caja", jPanel4);

        Tablaprestar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Su producto", "Mi producto", "Fecha de cambio", "Saldo pendiente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(Tablaprestar);

        btnprestar.setText("Prestar");
        btnprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprestarActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre Empresario");

        jLabel9.setText("Su producto");

        jLabel10.setText("Mi producto");

        jLabel11.setText("Fecha Prestamo");

        suproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suproductoActionPerformed(evt);
            }
        });

        miproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miproductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnprestar)
                .addGap(227, 227, 227))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suproducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tfechaprestar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(miproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nombreprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfechaprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btnprestar)
                .addGap(29, 29, 29))
        );

        pags.addTab("Prestamo", jPanel5);

        jLabel2.setText("Producto");

        Tnombrecliente.setText("Nombre Cliente");
        Tnombrecliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TnombreclienteFocusGained(evt);
            }
        });
        Tnombrecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnombreclienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Cliente");

        Tnombreproducto.setText("Nombre Producto");
        Tnombreproducto.setEnabled(false);
        Tnombreproducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TnombreproductoFocusGained(evt);
            }
        });
        Tnombreproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnombreproductoActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha");

        btnvenderfinal.setText("Vender");
        btnvenderfinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvenderfinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(spinerventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(tfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tnombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnvenderfinal)))
                .addContainerGap(246, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(Tnombreproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(247, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(spinerventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(Tnombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnvenderfinal)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(Tnombreproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(329, Short.MAX_VALUE)))
        );

        pags.addTab("Venta", jPanel3);

        jLabel1.setText("Inventario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 468, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pags, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pags, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TnombreclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnombreclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnombreclienteActionPerformed

    private void TnombreproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnombreproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnombreproductoActionPerformed

    private void btnvenderfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvenderfinalActionPerformed
        
        if (Tnombreproducto.getText().equals("") || ((int)spinerventa.getValue()) == 0 || Tnombrecliente.getText().equals("")
                ||tfecha.getCalendar() == null) {
            JOptionPane.showMessageDialog(this,"Llene todos los campos");
        }else{
            
            int año = tfecha.getCalendar().get(Calendar.YEAR);
            int mes = tfecha.getCalendar().get(Calendar.MONTH);
            int dia = tfecha.getCalendar().get(Calendar.DAY_OF_MONTH);
            String fecha = "" + año + "-" + mes + "-" + dia;
            conexion.vender(Tnombreproducto.getText(),(int)spinerventa.getValue(),Tnombrecliente.getText(),fecha);
            conexion.obtenerTablacaja(modeloCaja);
            JOptionPane.showMessageDialog(this,"Vendido!");
            Tnombreproducto.setText("");
            Tnombrecliente.setText("");
            spinerventa.setValue(0);
            tfecha.setCalendar(null);
        }
    }//GEN-LAST:event_btnvenderfinalActionPerformed

    private void TnombreproductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TnombreproductoFocusGained
    }//GEN-LAST:event_TnombreproductoFocusGained

    private void TnombreclienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TnombreclienteFocusGained
        Tnombrecliente.setText("");
    }//GEN-LAST:event_TnombreclienteFocusGained

    private void tfnombreclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnombreclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnombreclienteActionPerformed

    private void tftelefonoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftelefonoclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftelefonoclienteActionPerformed

    private void tfemailclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfemailclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfemailclienteActionPerformed

    private void btagregarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btagregarclienteActionPerformed
        
            if (!tfnombrecliente.getText().equals("") && !tftelefonocliente.getText().equals("") && !tfemailcliente.getText().equals("")) {
                cliente.setNombres(tfnombrecliente.getText());
                cliente.setTelefono(tftelefonocliente.getText());
                cliente.setEmail(tfemailcliente.getText());
                conexion.agragarCliente(cliente);
                modeloClientes = conexion.obtenerTablacliente(modeloClientes);
                
                limpiar();
            }if(tfnombrecliente.getText().equals("")||tftelefonocliente.getText().equals("") || tfemailcliente.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Llene todos los campos");

            }
        
    }//GEN-LAST:event_btagregarclienteActionPerformed

    private void btnCambiarstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarstockActionPerformed
        conexion.cambairstock(id_producto, (int) stockspin.getValue());
        conexion.obtenerTablaproducto(modeloProductos);
    }//GEN-LAST:event_btnCambiarstockActionPerformed

    private void btnvenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvenderActionPerformed
        pags.setSelectedIndex(4);
        Tnombreproducto.setText(nombreproducto);
    }//GEN-LAST:event_btnvenderActionPerformed

    private void suproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suproductoActionPerformed

    private void miproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miproductoActionPerformed

    private void btnprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprestarActionPerformed
        if (nombreprestar.getText().equals("")|| suproducto.getText().equals("")|| miproducto.getText().equals("")
                ||tfechaprestar.getCalendar() == null) {
            JOptionPane.showMessageDialog(this,"Llene todos los campos");
        }else{
            if(conexion.existeproducto(suproducto.getText())&&conexion.existeproducto(miproducto.getText())){
                int año = tfechaprestar.getCalendar().get(Calendar.YEAR);
                int mes = tfechaprestar.getCalendar().get(Calendar.MONTH);
                int dia = tfechaprestar.getCalendar().get(Calendar.DAY_OF_MONTH);
                String fecha = "" + año + "-" + mes + "-" + dia;
                conexion.prestar(nombreprestar.getText(),suproducto.getText(),miproducto.getText(),fecha);
                limpiar();
                modeloPrestar = conexion.obtenerTablaprestar(modeloPrestar);
                tfechaprestar.setCalendar(null);
            }else{JOptionPane.showMessageDialog(this, "no existe ese preducto!");}
            
        }
    }//GEN-LAST:event_btnprestarActionPerformed

    private void btnreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportesActionPerformed
        String fecha1 = JOptionPane.showInputDialog("Ingrese las fechas del reporte \n"
                + "Fecha 1 :Año-mes-dia");
        String fecha2 = JOptionPane.showInputDialog("Ingrese las fechas del reporte \n"
                + "Fecha 2 :Año-mes-dia");
        
        JOptionPane.showMessageDialog(this, "REPORTES \n"
                + "El reporte es: \n"
                + conexion.reporte(fecha1, fecha2) + " Pesos"
                , "Reportes", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnreportesActionPerformed
    
    private void limpiar (){
        tfnombrecliente.setText("");
        tftelefonocliente.setText("");
        tfemailcliente.setText("");
        nombreprestar.setText("");
        suproducto.setText("");
        miproducto.setText("");
    }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablacaja;
    private javax.swing.JTable Tablaclientes;
    private javax.swing.JTable Tablaprestar;
    private javax.swing.JTable Tablaproductos;
    private javax.swing.JTextField Tnombrecliente;
    private javax.swing.JTextField Tnombreproducto;
    private javax.swing.JButton btagregarcliente;
    private javax.swing.JButton btnCambiarstock;
    private javax.swing.JButton btnprestar;
    private javax.swing.JButton btnreportes;
    private javax.swing.JButton btnvender;
    private javax.swing.JButton btnvenderfinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelstock;
    private javax.swing.JTextField miproducto;
    private javax.swing.JTextField nombreprestar;
    private javax.swing.JTabbedPane pags;
    private javax.swing.JSpinner spinerventa;
    private javax.swing.JSpinner stockspin;
    private javax.swing.JTextField suproducto;
    private com.toedter.calendar.JDateChooser tfecha;
    private com.toedter.calendar.JDateChooser tfechaprestar;
    private javax.swing.JTextField tfemailcliente;
    private javax.swing.JTextField tfnombrecliente;
    private javax.swing.JTextField tftelefonocliente;
    // End of variables declaration//GEN-END:variables
}
